name: Deployment exercise 2
on: push
jobs:
  # job 2
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Code Linting
        run: npm run lint
  # job 2
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Execute tests
        run: npm run test
  # job 3
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
  # job 4
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci      
      - name: Deploy code
        run: echo "Deploying to remote serer..."